# Generated by Django 3.0.5 on 2020-04-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200412_0008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_info',
        ),
    ]
