# Generated by Django 3.0.5 on 2020-04-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_info',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
