# Generated by Django 3.0.5 on 2020-04-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eadlogin', '0002_login_info_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_info',
            name='username',
        ),
    ]
